# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.7.0"

package:
  name: cocat
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/c/cocat/cocat-${{ version }}.tar.gz
    sha256: e61a5f623f1be3838d5d176b6759ee50567c3a71e36b7e05f4a071b6d6d2ea27

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - uv-build
  run:
    - python >=${{ python_min }}
    - pycrdt >=0.12.40,<0.13.0
    - pydantic >=2.12.0,<3.0.0
    - typing_extensions >=4.15.0,<5.0.0
    - wiredb >=0.7.1,<0.8.0
    - cyclopts >=4.0.0,<5.0.0
    - wire-file >=0.7.1,<0.8.0
    - wire-websocket >=0.7.1,<0.8.0
    - httpx >=0.28.1,<0.29.0
    - simpleeval >=1.0.3,<2.0.0
    - rich

tests:
  - python:
      imports: cocat
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/SciQLop/cocat
  summary: CRDT-based tscat.

extra:
  recipe-maintainers:
    - davidbrochart
