# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.3.1"

package:
  name: cocat
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/c/cocat/cocat-${{ version }}.tar.gz
    sha256: 602e690dad12ab82818f25c95083804a7e602f3057f1a28da3c2330d8f3000f6

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - uv-build
  run:
    - python >=${{ python_min }}
    - pycrdt >=0.12.40,<0.13.0
    - pydantic >=2.12.0,<3.0.0
    - typing_extensions >=4.15.0,<5.0.0
    - wiredb >=0.4.0,<0.5.0

tests:
  - python:
      imports: cocat
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/SciQLop/cocat
  summary: CRDT-based tscat.

extra:
  recipe-maintainers:
    - davidbrochart
